// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                       = require("bs-jest/lib/js/src/jest.js");
var Parser$BsLittleParser      = require("../src/parser.bs.js");
var Caml_builtin_exceptions    = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var ParseResult$BsLittleParser = require("../src/parseResult.bs.js");

Jest.test("rep", (function () {
        var result = Parser$BsLittleParser.stringParser("abc", /* record */[
              /* text */"abcabc  abc",
              /* index */0,
              /* whitespace */" "
            ]);
        var match = ParseResult$BsLittleParser.getResult(result);
        if (match) {
          Jest.Expect[/* toEqual */12]("abc")(Jest.Expect[/* expect */0](match[0]));
          return Jest.Expect[/* toBe */2](3)(Jest.Expect[/* expect */0](ParseResult$BsLittleParser.getIndex(result)));
        } else {
          throw [
                Caml_builtin_exceptions.assert_failure,
                [
                  "test.ml",
                  14,
                  14
                ]
              ];
        }
      }));

/*  Not a pure module */
