// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                       = require("bs-jest/lib/js/src/jest.js");
var Parser$BsLittleParser      = require("../src/parser.bs.js");
var Caml_builtin_exceptions    = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var ParseResult$BsLittleParser = require("../src/parseResult.bs.js");

Jest.test("parse", (function () {
        var result = Parser$BsLittleParser.stringParser("abc", /* record */[
              /* text */"abcdefg",
              /* index */0,
              /* whitespace */" "
            ]);
        var match = ParseResult$BsLittleParser.getResult(result);
        if (match) {
          Jest.Expect[/* toEqual */12]("abc")(Jest.Expect[/* expect */0](match[0]));
          return Jest.Expect[/* toBe */2](3)(Jest.Expect[/* expect */0](ParseResult$BsLittleParser.getIndex(result)));
        } else {
          throw [
                Caml_builtin_exceptions.assert_failure,
                [
                  "test.ml",
                  14,
                  14
                ]
              ];
        }
      }));

Jest.test("<*>", (function () {
        var abc = function (param) {
          return Parser$BsLittleParser.stringParser("abc", param);
        };
        var def = function (param) {
          return Parser$BsLittleParser.stringParser("def", param);
        };
        var result = Parser$BsLittleParser.$less$star$great(abc, def)(/* record */[
              /* text */"abcdefg",
              /* index */0,
              /* whitespace */" "
            ]);
        var match = ParseResult$BsLittleParser.getResult(result);
        if (match) {
          Jest.Expect[/* toEqual */12](/* tuple */[
                  "abc",
                  "def"
                ])(Jest.Expect[/* expect */0](match[0]));
          return Jest.Expect[/* toBe */2](6)(Jest.Expect[/* expect */0](ParseResult$BsLittleParser.getIndex(result)));
        } else {
          throw [
                Caml_builtin_exceptions.assert_failure,
                [
                  "test.ml",
                  26,
                  14
                ]
              ];
        }
      }));

Jest.test("<|>", (function () {
        var abc = function (param) {
          return Parser$BsLittleParser.stringParser("abx", param);
        };
        var def = function (param) {
          return Parser$BsLittleParser.stringParser("abc", param);
        };
        var result = Parser$BsLittleParser.$less$pipe$great(abc, def)(/* record */[
              /* text */"abcdefg",
              /* index */0,
              /* whitespace */" "
            ]);
        var match = ParseResult$BsLittleParser.getResult(result);
        if (match) {
          Jest.Expect[/* toEqual */12]("abc")(Jest.Expect[/* expect */0](match[0]));
          return Jest.Expect[/* toBe */2](3)(Jest.Expect[/* expect */0](ParseResult$BsLittleParser.getIndex(result)));
        } else {
          throw [
                Caml_builtin_exceptions.assert_failure,
                [
                  "test.ml",
                  38,
                  14
                ]
              ];
        }
      }));

/*  Not a pure module */
