// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Parser$BsParserCombinator = require("./parser.bs.js");

var input = /* record */[
  /* text */"abcabc  abc",
  /* index */0,
  /* whitespace */" "
];

function ab(param) {
  return Parser$BsParserCombinator.stringParser("ab", param);
}

function abc(param) {
  return Parser$BsParserCombinator.stringParser("abc", param);
}

console.log(Parser$BsParserCombinator.rep(abc, input));

exports.input = input;
exports.ab    = ab;
exports.abc   = abc;
/*  Not a pure module */
