// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function getResult(parseResult) {
  if (parseResult.tag) {
    return /* None */0;
  } else {
    return /* Some */[parseResult[0]];
  }
}

function getIndex(parseResult) {
  return parseResult[1][/* index */1];
}

function map(f, parseResult) {
  if (parseResult.tag) {
    return /* ParseFailure */Block.__(1, [
              parseResult[0],
              parseResult[1]
            ]);
  } else {
    return /* ParseSuccess */Block.__(0, [
              Curry._1(f, parseResult[0]),
              parseResult[1]
            ]);
  }
}

exports.getResult = getResult;
exports.getIndex  = getIndex;
exports.map       = map;
/* No side effect */
